export const unicodeCjkRanges: Record<string, string> = {
  cjkUnifiedIdeographs: '\\u4E00-\\u9FFF',
  cjkUnifiedIdeographsExtensionA: '\\u3400-\\u4DBF',
  cjkUnifiedIdeographsExtensionB: '\\u{20000}-\\u{2A6DF}',
  cjkUnifiedIdeographsExtensionC: '\\u{2A700}-\\u{2B73F}',
  cjkUnifiedIdeographsExtensionD: '\\u{2B740}-\\u{2B81F}',
  cjkUnifiedIdeographsExtensionE: '\\u{2B820}-\\u{2CEAF}',
  cjkUnifiedIdeographsExtensionF: '\\u{2CEB0}-\\u{2EBEF}',
  cjkUnifiedIdeographsExtensionG: '\\u{30000}-\\u{3134F}',
  cjkUnifiedIdeographsExtensionH: '\\u{31350}-\\u{323AF}',
  cjkUnifiedIdeographsExtensionI: '\\u{2EBF0}-\\u{2EE5F}',
  cjkRadicalsSupplement: '\\u2E80-\\u2EFF',
  kangxiRadicals: '\\u2F00-\\u2FDF',
  ideographicDescriptionCharacters: '\\u2FF0-\\u2FFF',
  cjkSymbolsAndPunctuation: '\\u3000-\\u303F',
  cjkStrokes: '\\u31C0-\\u31EF',
  enclosedCjkLettersAndMonths: '\\u3200-\\u32FF',
  cjkCompatibility: '\\u3300-\\u33FF',
  cjkCompatibilityIdeographs: '\\uF900-\\uFAFF',
  cjkCompatibilityForms: '\\uFE30-\\uFE4F',
  enclosedIdeographicSupplement: '\\u{1F200}-\\u{1F2FF}',
  cjkCompatibilityIdeographsSupplement: '\\u{2F800}-\\u{2FA1F}',
  halfWidthAndFullWidthForms: '\\uFF00-\\uFFEF',
  verticalForms: '\\uFE10-\\uFE1F',
};
