export const unicodeCjkRanges = {
  cjkUnifiedIdeographs: String.raw`\u4E00-\u9FFF`,
  cjkUnifiedIdeographsExtensionA: String.raw`\u3400-\u4DBF`,
  cjkUnifiedIdeographsExtensionB: String.raw`\u{20000}-\u{2A6DF}`,
  cjkUnifiedIdeographsExtensionC: String.raw`\u{2A700}-\u{2B73F}`,
  cjkUnifiedIdeographsExtensionD: String.raw`\u{2B740}-\u{2B81F}`,
  cjkUnifiedIdeographsExtensionE: String.raw`\u{2B820}-\u{2CEAF}`,
  cjkUnifiedIdeographsExtensionF: String.raw`\u{2CEB0}-\u{2EBEF}`,
  cjkUnifiedIdeographsExtensionG: String.raw`\u{30000}-\u{3134F}`,
  cjkUnifiedIdeographsExtensionH: String.raw`\u{31350}-\u{323AF}`,
  cjkUnifiedIdeographsExtensionI: String.raw`\u{2EBF0}-\u{2EE5F}`,
  cjkRadicalsSupplement: String.raw`\u2E80-\u2EFF`,
  kangxiRadicals: String.raw`\u2F00-\u2FDF`,
  ideographicDescriptionCharacters: String.raw`\u2FF0-\u2FFF`,
  cjkSymbolsAndPunctuation: String.raw`\u3000-\u303F`,
  cjkStrokes: String.raw`\u31C0-\u31EF`,
  enclosedCjkLettersAndMonths: String.raw`\u3200-\u32FF`,
  cjkCompatibility: String.raw`\u3300-\u33FF`,
  cjkCompatibilityIdeographs: String.raw`\uF900-\uFAFF`,
  cjkCompatibilityForms: String.raw`\uFE30-\uFE4F`,
  enclosedIdeographicSupplement: String.raw`\u{1F200}-\u{1F2FF}`,
  cjkCompatibilityIdeographsSupplement: String.raw`\u{2F800}-\u{2FA1F}`,
  halfWidthAndFullWidthForms: String.raw`\uFF00-\uFFEF`,
  verticalForms: String.raw`\uFE10-\uFE1F`,
} satisfies Record<string, string>;
